-- Hand-authored, not generated by `prisma migrate dev --create-only`: local
-- Postgres (Docker) was unreachable in this session, so this migration was
-- written by hand, field-for-field against docs/PHASE6_IMPLEMENTATION_PLAN.md
-- Section 14 and mirroring the exact DDL shape of the two precedent
-- migrations for pgvector-backed chunk tables:
-- 20260809124823_add_contract_chunks_investigator and
-- 20260811213025_add_organization_brain_chunks. Per this project's own
-- established discipline (see both precedent files' header comments), run
-- `npx prisma migrate dev --create-only` again once the dev database is
-- reachable to cross-check this file against Prisma's own diff before it is
-- ever applied — do not apply this migration as-is without that check.
--
-- The "vector" extension is not (re-)created here: it was already created
-- by 20260809124823_add_contract_chunks_investigator and is not dropped by
-- either precedent migration, so a fresh database applying all migrations
-- in order already has it by the time this one runs.

-- CreateEnum
CREATE TYPE "LegalSourceType" AS ENUM ('LEGISLATION', 'CODE', 'DECREE', 'JURISPRUDENCE', 'DOCTRINE', 'ADMINISTRATIVE_GUIDANCE');

-- CreateEnum
CREATE TYPE "LegalAuthorityTier" AS ENUM ('BINDING_LEGISLATION', 'JURISPRUDENCE', 'DOCTRINE', 'ADMINISTRATIVE_GUIDANCE');

-- CreateEnum
CREATE TYPE "LegalStatus" AS ENUM ('IN_FORCE', 'REPEALED', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "LegalLicenseStatus" AS ENUM ('DEVELOPMENT_ONLY', 'UNDER_REVIEW', 'CLEARED_FOR_PRODUCTION');

-- CreateTable
-- No organization_id column, anywhere, under any name — the Legal Knowledge
-- Base is the first structurally global (non-organization-scoped) table in
-- this schema, per docs/DOMAIN_REVIEW_BACKLOG.md Decision 2.
CREATE TABLE "legal_sources" (
    "id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "source_type" "LegalSourceType" NOT NULL,
    "authority_tier" "LegalAuthorityTier" NOT NULL,
    "instrument_number" TEXT NOT NULL,
    "language" TEXT NOT NULL DEFAULT 'ar',
    "jurisdiction" TEXT NOT NULL DEFAULT 'LB',
    "promulgating_authority" TEXT NOT NULL,
    "compiler_source" TEXT NOT NULL,
    "source_url" TEXT NOT NULL,
    "raw_snapshot_storage_key" TEXT,
    "official_gazette_number" TEXT,
    "official_gazette_publish_date" DATE,
    "official_gazette_page" TEXT,
    "promulgation_date" DATE,
    "legal_status" "LegalStatus" NOT NULL DEFAULT 'IN_FORCE',
    "license_status" "LegalLicenseStatus" NOT NULL DEFAULT 'DEVELOPMENT_ONLY',
    "last_verified_at" TIMESTAMP(3),
    "deleted_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "legal_sources_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- content_tsv is a generated column (Prisma has no syntax for this — same
-- hand-written precedent as contract_chunks/organization_brain_chunks),
-- deliberately using 'simple' rather than 'english': the five Phase 6
-- source documents are Arabic-only, and PostgreSQL's built-in text-search
-- configurations don't include an Arabic dictionary/stemmer. Copying
-- 'english' unchanged from the two existing precedents would silently
-- mis-tokenize this corpus's content — this is the one required deviation
-- from those two migrations' pattern, not a stylistic choice.
CREATE TABLE "legal_chunks" (
    "id" UUID NOT NULL,
    "legal_source_id" UUID NOT NULL,
    "chunk_index" INTEGER NOT NULL,
    "heading_path" TEXT,
    "article_number" TEXT,
    "content" TEXT NOT NULL,
    "token_count" INTEGER,
    "amending_instrument" TEXT,
    "amendment_effective_date" DATE,
    "legal_status" "LegalStatus" NOT NULL,
    "license_status" "LegalLicenseStatus" NOT NULL,
    "embedding" vector(1536),
    "content_tsv" tsvector GENERATED ALWAYS AS (to_tsvector('simple', "content")) STORED,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "legal_chunks_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "legal_sources_source_type_idx" ON "legal_sources"("source_type");

-- CreateIndex
CREATE INDEX "legal_sources_legal_status_idx" ON "legal_sources"("legal_status");

-- CreateIndex
CREATE INDEX "legal_sources_license_status_idx" ON "legal_sources"("license_status");

-- CreateIndex
CREATE UNIQUE INDEX "legal_chunks_legal_source_id_chunk_index_key" ON "legal_chunks"("legal_source_id", "chunk_index");

-- CreateIndex
CREATE INDEX "legal_chunks_legal_source_id_idx" ON "legal_chunks"("legal_source_id");

-- CreateIndex
-- Typed, indexed article lookup — distinct from heading_path's free-text
-- display label, specifically so an exact article-number query
-- (WHERE article_number = $1) doesn't require a fuzzy string match.
CREATE INDEX "legal_chunks_article_number_idx" ON "legal_chunks"("article_number");

-- CreateIndex
CREATE INDEX "legal_chunks_license_status_idx" ON "legal_chunks"("license_status");

-- CreateIndex
-- Full-text leg of hybrid retrieval — 'simple' config (see note above on
-- the legal_chunks table), not the 'english' config contract_chunks and
-- organization_brain_chunks use.
CREATE INDEX "legal_chunks_content_tsv_idx" ON "legal_chunks" USING GIN ("content_tsv");

-- CreateIndex
-- Vector similarity leg — same HNSW/cosine configuration as contract_chunks
-- and organization_brain_chunks.
CREATE INDEX "legal_chunks_embedding_idx" ON "legal_chunks" USING hnsw ("embedding" vector_cosine_ops);

-- AddForeignKey
-- Only foreign key on this table: no organization_id, so no second FK the
-- way contract_chunks/organization_brain_chunks each have. Fires only on a
-- genuine hard delete of a LegalSource row (rare, operator-only) — soft
-- delete via LegalSource.deleted_at does not cascade at the database level
-- and must be filtered by the retrieval query itself (a Batch 4
-- responsibility, not this migration's).
ALTER TABLE "legal_chunks" ADD CONSTRAINT "legal_chunks_legal_source_id_fkey" FOREIGN KEY ("legal_source_id") REFERENCES "legal_sources"("id") ON DELETE CASCADE ON UPDATE CASCADE;
