import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../../components/ui/card";
import { WitnessStatusBadge } from "./WitnessStatusBadge";
import type { WitnessInvitation } from "./types";

interface WitnessInvitationsTableProps {
  invitations: WitnessInvitation[];
  onRowClick: (invitation: WitnessInvitation) => void;
}

const TABLE_HEADERS = [
  "Contract",
  "Witness",
  "Generated By",
  "Created",
  "Expires",
  "Status",
  "Access Type",
  "Last Activity",
] as const;

/**
 * Table of all active witness invitations.
 * Clicking any row opens the WitnessAccessDetailsSidebar.
 * Desktop: full 8-column table. Mobile: stacked card list.
 */
export function WitnessInvitationsTable({ invitations, onRowClick }: WitnessInvitationsTableProps) {
  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-base font-semibold">Active Witness Invitations</CardTitle>
            <CardDescription>All witness access links across your contracts.</CardDescription>
          </div>
          <span className="rounded-full bg-muted px-2.5 py-0.5 text-xs font-medium text-muted-foreground">
            {invitations.length} Invitations
          </span>
        </div>
      </CardHeader>

      <CardContent className="p-0">
        {/* ── Desktop table ── */}
        <div className="hidden overflow-x-auto lg:block">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border bg-muted/30">
                {TABLE_HEADERS.map((h) => (
                  <th
                    key={h}
                    className="whitespace-nowrap px-4 py-3 text-left text-xs font-medium text-muted-foreground"
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {invitations.map((inv) => (
                <InvitationRow
                  key={inv.id}
                  invitation={inv}
                  onClick={() => onRowClick(inv)}
                />
              ))}
            </tbody>
          </table>
        </div>

        {/* ── Mobile card list ── */}
        <ul className="divide-y divide-border lg:hidden">
          {invitations.map((inv) => (
            <InvitationCard
              key={inv.id}
              invitation={inv}
              onClick={() => onRowClick(inv)}
            />
          ))}
        </ul>
      </CardContent>
    </Card>
  );
}

// ─── Desktop row ──────────────────────────────────────────────────────────────

interface RowProps {
  invitation: WitnessInvitation;
  onClick: () => void;
}

function InvitationRow({ invitation: inv, onClick }: RowProps) {
  return (
    <tr
      role="button"
      tabIndex={0}
      onClick={onClick}
      onKeyDown={(e) => e.key === "Enter" && onClick()}
      className="cursor-pointer transition-colors hover:bg-muted/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring"
    >
      <td className="px-4 py-3">
        <p className="font-medium text-foreground">{inv.contractName}</p>
        <p className="text-xs text-muted-foreground">{inv.contractId}</p>
      </td>
      <td className="px-4 py-3">
        <p className="font-medium text-foreground">{inv.witnessName}</p>
        <p className="text-xs text-muted-foreground">{inv.witnessEmail}</p>
      </td>
      <td className="whitespace-nowrap px-4 py-3 text-sm text-muted-foreground">{inv.generatedBy}</td>
      <td className="whitespace-nowrap px-4 py-3 text-sm text-muted-foreground">{inv.created}</td>
      <td className="px-4 py-3">
        <p className="whitespace-nowrap text-sm text-muted-foreground">{inv.expires}</p>
        <p className="text-xs text-muted-foreground">{inv.expiresLabel}</p>
      </td>
      <td className="px-4 py-3"><WitnessStatusBadge status={inv.status} /></td>
      <td className="whitespace-nowrap px-4 py-3 text-sm text-muted-foreground">{inv.accessType}</td>
      <td className="whitespace-nowrap px-4 py-3 text-sm text-muted-foreground">{inv.lastAction}</td>
    </tr>
  );
}

// ─── Mobile card ──────────────────────────────────────────────────────────────

function InvitationCard({ invitation: inv, onClick }: RowProps) {
  return (
    <li
      role="button"
      tabIndex={0}
      onClick={onClick}
      onKeyDown={(e) => e.key === "Enter" && onClick()}
      className="flex cursor-pointer flex-col gap-2 px-4 py-4 transition-colors hover:bg-muted/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring"
    >
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0">
          <p className="truncate font-medium text-foreground">{inv.contractName}</p>
          <p className="text-xs text-muted-foreground">{inv.contractId}</p>
        </div>
        <WitnessStatusBadge status={inv.status} />
      </div>
      <div className="text-sm text-foreground">
        {inv.witnessName}
        <span className="ml-1 text-xs text-muted-foreground">({inv.witnessEmail})</span>
      </div>
      <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground">
        <span>By {inv.generatedBy}</span>
        <span>Expires {inv.expiresLabel}</span>
        <span>{inv.accessType}</span>
        <span>{inv.lastAction}</span>
      </div>
    </li>
  );
}