import { Button } from "../../components/ui/button";
import { WitnessStatusBadge } from "./WitnessStatusBadge";
import { CopyIcon, RefreshIcon } from "../shared/icons";
import type { WitnessInvitation } from "./types";

interface WitnessAccessDetailsSidebarProps {
  invitation: WitnessInvitation | null;
  onClose: () => void;
}


export function WitnessAccessDetailsSidebar({
  invitation,
  onClose,
}: WitnessAccessDetailsSidebarProps) {
  if (!invitation) return null;

  function handleCopy() {
    navigator.clipboard.writeText(invitation!.url);
  }

  return (
    <>
      {/* Blur overlay — clicking it closes the sidebar */}
      <div
        className="fixed inset-0 z-40 bg-background/40 backdrop-blur-sm"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Sidebar panel */}
      <aside className="fixed right-0 top-0 z-50 flex h-full w-full max-w-sm flex-col border-l border-border bg-card shadow-2xl">

        {/* ── Header ── */}
        <div className="flex items-start justify-between border-b border-border p-5">
          <div className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} className="h-4 w-4">
                <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125" />
              </svg>
            </div>
            <div>
              <p className="text-sm font-semibold text-foreground">Witness Access Details</p>
              <p className="text-xs text-muted-foreground">{invitation.id}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-md p-1 text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
            aria-label="Close sidebar"
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="h-4 w-4">
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* ── Scrollable body ── */}
        <div className="flex-1 overflow-y-auto">

          {/* CONTRACT INFORMATION */}
          <Section title="CONTRACT INFORMATION">
            <DetailRow label="Contract Title" value={invitation.contractName} bold />
            <DetailRow label="Reference"      value={invitation.contractId} />
            <DetailRow label="Status">
              <WitnessStatusBadge status={invitation.status} />
            </DetailRow>
            <DetailRow label="Expiration Date" value={invitation.expires} />
          </Section>

          <Divider />

          {/* WITNESS INFORMATION */}
          <Section title="WITNESS INFORMATION">
            <DetailRow label="Name"        value={invitation.witnessName} bold />
            <DetailRow label="Email"       value={invitation.witnessEmail} />
            <DetailRow label="Access Type" value={invitation.accessType} />
          </Section>

          <Divider />

          {/* ACCESS INFORMATION */}
          <Section title="ACCESS INFORMATION">
            <DetailRow label="Generated Date"  value={invitation.generatedDate} />
            <DetailRow label="Generated By"    value={invitation.generatedBy} />
            <DetailRow label="Expiration Date" value={invitation.expires} />
            <DetailRow label="Current Status">
              <WitnessStatusBadge status={invitation.status} />
            </DetailRow>
            <DetailRow label="Last Access Time" value={invitation.lastAction} />
          </Section>

          {/* URL row */}
          <div className="px-5 pb-4">
            <div className="flex items-center gap-2 rounded-lg border border-border bg-muted/30 px-3 py-2.5">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} className="h-4 w-4 shrink-0 text-muted-foreground">
                <path strokeLinecap="round" strokeLinejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244" />
              </svg>
              <span className="flex-1 truncate font-mono text-xs text-muted-foreground">
                {invitation.url}
              </span>
            </div>
          </div>
        </div>

        {/* ── Footer actions ── */}
        <div className="border-t border-border p-4 space-y-2">
          <div className="grid grid-cols-2 gap-2">
            <Button variant="outline" size="sm" className="gap-1.5 w-full" onClick={handleCopy}>
              <CopyIcon />
              Copy Link
            </Button>
            <Button variant="outline" size="sm" className="gap-1.5 w-full">
              <RefreshIcon />
              Regenerate
            </Button>
          </div>
          <Button
            variant="destructive"
            size="sm"
            className="w-full gap-1.5"
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} className="h-4 w-4">
              <path strokeLinecap="round" strokeLinejoin="round" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
            </svg>
            Revoke Access
          </Button>
        </div>
      </aside>
    </>
  );
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="px-5 py-4">
      <p className="mb-3 text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
        {title}
      </p>
      <div className="space-y-3">{children}</div>
    </div>
  );
}

function Divider() {
  return <div className="border-t border-border" />;
}

function DetailRow({
  label,
  value,
  bold,
  children,
}: {
  label: string;
  value?: string;
  bold?: boolean;
  children?: React.ReactNode;
}) {
  return (
    <div className="flex items-start justify-between gap-4">
      <span className="shrink-0 text-xs text-muted-foreground">{label}</span>
      {children ?? (
        <span className={`text-right text-xs ${bold ? "font-semibold text-foreground" : "text-foreground"}`}>
          {value}
        </span>
      )}
    </div>
  );
}
